### PR TITLE
Improve logging upon failure

### PR DESCRIPTION
**Pull request by ZainRizvi**

### CODE REVIEW

**Comment by enomic** [comment]
#approve 377ff34f72bd497abf6f4568a8c6c15aab1c63419d18d1af90a8fa6be26d971900bb7ab540b4af186e55b535a5fb809fa51153305acab5ccf7912aebe53fb03cdbc460c34c1ca18c8a17226c9107df4e9b70c425614e5c653757a5aeed951067a788dd1a57dd67d9732cd39199d0348a333c88b615730113494c790bde7472ed60ca71738ef80f1c68de6fca016d56d482797b6c8fdf0b2eab02a05a1647bb80625db9b4bf0e6dbeff15219796a76f3c5c006e669711930190bbe57cbff8d55d05cc453dad1fb3f5a89e2c6379a0525775c7afbf4916a4510b361c63924f90326eb8fbdca03d6a385bf0bce959541552623a9ea33d9230028dcf37d5bb9f734b

**Comment by enomic** [comment]
Actually this can't be approved until you rebase :-(

Somebody should fix this! Adding keys by hand like this is really unpleasant

**Comment by ZainRizvi** [comment]
Hey enomic, this pull request has been rebased and is ready to be pulled :)

**Comment by ZainRizvi** [comment]
#approve dfc5191ea4842345fdcea065c85bf98ef3dc57b2562278d57892303092960aac002b07af5e0babb0f9cf95b9891ec1819491b16066a6fbd4c3c401b321da40539cca8df63b388570380a82e039839843e31406c5a169cd5e46b169c39ec967012f9788466c41926f51a802e8b2fcd2503211d047a2891c5a872b439c57fe7b8dc17c53f12b684c97dca62b8ce65ee1b4c80ab32073010bd9ff37a4d4f46e19fc7a00cc1c481a401bafe28ffb01fa3f50a409aa225c59b384a59eeb297324db31504012d73ad6e4d15ff6e99ceb0f830de2910a9bb79e94d0798bfb669e68d1ef62075148fed9a5cce06f2ce3543a78f31175ede0c8e69888fbc065ea5f6d7db8

**Comment by ZainRizvi** [comment]
Wait, no, I'm not a hero yet. Someone please approve this request!

**Comment by enomic** [comment]
#approve 217f3de1dc59f8dce4600591fff884945563dc3b19acc7f8fc68f32abc7b4b5fce7d4df4818e6a4ce723c74cd6ea8c539ef823dc397f9719fda55f999077afba1e3da16198d4e2a2b1a23400d5c8822646682aa1a6d2f3f3eb1095e3565be19ca0cf1a9e56d1b2c17e0d2f2c570a63910048d143784c7364ccb1fd04441e5c18db67d59093328604282fccd8c6bbc81f80f124f54062916458bfa648de45b668a1a9afa5799c2fe2623c59cb792c069f24164dde508fc44cb9cfc6699b5ba9af72cf43accb093b8861045eae620cc8fbcbc7b4fef0c1efa5af8d5b6ebaf4033921c47c93d317ed1021bfefa1832408b11ac516693947b16d3049e295ed5b6aa4

**Pull request merged**
