### PR TITLE
Possibly working gist logger

### PR DESCRIPTION
**Pull request by cinderblock**

### CODE REVIEW

**Comment by cinderblock** [comment]
#approve 434d66512bdbf1ff4bcc0731944764594890c260e28251fbba4c6dfbc9f7c266aa2e296689c4e7458bef7598fd0fd39bed435fca5d7f8064a191faeaaed354339c0665777d278c1c7c37f19d4ff7353f5d7d16d0c681ace8af090b420ab4a2570593b7249fa6c11fb9df00f7de0f4ce182abff96fdf4f088dae4a7ffca609f4c5e4dd806137115d558d65aae57392062be600223e3f050ac1944b06235f30032cc47279d9ab2a65ab0d3c7fee0eab239fce4f69c308a43c352ab68b4f5199ede9204d2bc4f5a60ee1127fcc6779142ebbd2f2adaecd91f1d976573bbd5b0aa7706bf6f9e149e8f28fb4aa3116a422bb4f45d6255d3369a15f217c21c86941711

**Comment by cinderblock** [comment]
test

**Comment by enomic** [comment]
hmm, it seems this broke the app.

```
Error: Cannot find module './logger'
```

Can you fix it up? I'll merge the PR on gh and we'll be online again

**Comment by cinderblock** [comment]
#17

**Pull request merged**
