### PR TITLE
Add .gitignore entries for vim and kdiff

### PR DESCRIPTION
**Pull request by ghost**
# approve 32d37f80144d106c7c77f4c6abdb11b80f890b3d4faa957df64957095e9ed2d9c5266d068d12b62f4ae699226ce6ee7267d28628e1fff16f8b354b22e2c7ddd73bc1d1904b81b69b4e44b55fc305a864356fdebbebfbab4f612ac149d0ab35fcd6a8ad57664ea5e6d728931772b42603bd3808663284d0822ab850e38722d341b0ea3275d9d9f839a9c72c5d6946a61f6f2672dccb973d724cda2317674b8bac9674941c5880becb2ef69d0198473aabbb58529e37fe9e1c3e9b60d33c85de7ec744fae1f68d8a901cc5bef82a697f9e37ec3588e726fe7fec16defa069700bfa169851c7943be2ba404ef7ac9e5fdc14881f7e595e7cf587b71e6603a5e2626

### CODE REVIEW

**Comment by cinderblock** [comment]
#approve 32d37f80144d106c7c77f4c6abdb11b80f890b3d4faa957df64957095e9ed2d9c5266d068d12b62f4ae699226ce6ee7267d28628e1fff16f8b354b22e2c7ddd73bc1d1904b81b69b4e44b55fc305a864356fdebbebfbab4f612ac149d0ab35fcd6a8ad57664ea5e6d728931772b42603bd3808663284d0822ab850e38722d341b0ea3275d9d9f839a9c72c5d6946a61f6f2672dccb973d724cda2317674b8bac9674941c5880becb2ef69d0198473aabbb58529e37fe9e1c3e9b60d33c85de7ec744fae1f68d8a901cc5bef82a697f9e37ec3588e726fe7fec16defa069700bfa169851c7943be2ba404ef7ac9e5fdc14881f7e595e7cf587b71e6603a5e2626

**Comment by enomic** [comment]
Output is here: https://gist.github.com/cbc5122afd5346fae915

**Comment by cinderblock** [comment]
I just re-posted your #approve as a comment. It seems you cannot immediately approve your own PR in in the initial comment.

**Comment by enomic** [comment]
Output is here: https://gist.github.com/046d3a930db623aaf24e

**Pull request merged**
