### PR TITLE
POST, not PUT...

### PR DESCRIPTION
**Pull request by cinderblock**

### CODE REVIEW

**Comment by cinderblock** [comment]
#approve 07dd6ff09fde74b630a3f5becd86af7043834642c832ec2c88ba8746e2ae680dd42040e408c0d6aaae5b0114618fd2b25bb401205b3c5f5ec593783c9597e4654961c25022de64d8d09ef0d867fd2912cc619ebc3f7eecabb4b088472cc43630c7bb6a068acc05261a76923f9be4764be3836b42e389305bcea8f774bae0c5b44a1528103f1a7bbb17cbe528ec5068a17e6b36a058ed9aef7c5823ef6137b08e2462e01986bffbaba7da337a616a5690a6ba370e73e3994c15ef4c2f1b8be5052459f87cf1b0ab92047dac5908ea942743eff3f74dedf09f6841882e62a4b293e2f8381e76695b902dfb7c9cabe014324c67eadf034603c35a58d53ffc2f61af

**Comment by cinderblock** [comment]
#approve this is a test

**Comment by enomic** [comment]
Output is here: https://gist.github.com/63af033f6bcf7b82dbe7

**Comment by cinderblock** [comment]
https://github.com/enomic/enomic/issues/17

**Pull request merged**
