### PR TITLE
Make regex that matches #approve more restrictive

### PR DESCRIPTION
**Pull request by cinderblock**
The service is commenting every time someone says #approve in a comment. Make it not so verbose.

### CODE REVIEW

**Comment by cinderblock** [comment]
Oops. This also references commits already in my previous PR. I need to branch better.

**Comment by ericvicenti** [comment]
#approve 0afa59e18308a4623a9bde077ec94467a20cf184172cf19421a21444a0475f1a4cc6290ba3587ee896a0ae9796b97f7cec6b6db7c5a1800b0955b6b77bc303801228a1f068769ae3394ad93197f1ff81d670d96951d88dc4840425c26e551f05e61148b2b91a71679c96d3ddbafad498c067201cbdced0743e797e95fd5ecc54e31f0bed78e5be47c56fe4561dcffc602ebc024267ca7bc2885592580ad1af56b48d9c3023fbc94aa9571d0c67b9881356ae70ca220c2e2bfb9cdd9fe4d8b99f0bda906965166d1f619720688b745ed77ff6655becdd2b1904d02da4ecf46d5e38c835eeb79ad84069b7ed9679fbec80869dd37cf8edbb729a53388272a57fbc

**Comment by enomic** [comment]
Output is here: https://gist.github.com/41e342a00f551d4e3723

**Comment by cinderblock** [comment]
@ZainRizvi Yeah! :smile:

**Comment by cinderblock** [comment]
If there aren't any objections in the next hour, or someone else does it for me, I'm going to #approve this (and #38) myself so that I can make a new PR that has a new double #approve feature!

**Comment by enomic** [comment]
Output is here: https://gist.github.com/4c021f0f1f589a770927

**Comment by cinderblock** [comment]
#approve 3c0d228a97572fa3ddddf4b4548721c0cb976d12b48748ed6d6e45e16d21844cf7d8f00a5df16626dbdf55ba961270e6f7732ca88f7dac71f77e3c67df27812a2257ea716edabef2861ff0cb966d296de15f5ececa055e7de0e501cd0be0c77064980458ae595b0b53dd8cf6055e0d5a8c7b2b9b9c31dada3d509a8fb2039e7604468b374b94cb26163cbaa582514ba88d4d0ea767c4c612d850f158cebb57281c99f970b2452ee4aca6e5076741a45db0bf0b3fe0b221cbd65229891f8729d440e07dee4c4e77500868fc566dc189e7c72d0344fc78ca9c4c03f620ad361e1b1659b98c67569718c3d05f74376671f204e19f7e864011d49615a379c9cc7b4e

**Comment by enomic** [comment]
Output is here: https://gist.github.com/f9cb171f8a80defd9e67

**Comment by cinderblock** [comment]
#approve test

**Comment by cinderblock** [comment]
#approve testasdfadsftestasdfadsftestasdfadsftestasdfadsftestasdfadsftestasdfadsftestasdfadsftestasdfadsftestasdfadsf

**Comment by enomic** [comment]
Already merged

Output is here: https://gist.github.com/b22fb5fa6e38b57caeb4

**Comment by cinderblock** [comment]
It works :smile:

**Pull request merged**
