### PR TITLE
Add .gitignore entries for vim and kdiff

### PR DESCRIPTION
**Pull request by ghost**
# authorize 1d07c3ab91a3e4b3ddaa88bc01219c6420f469f959360074ba0ee46ac290fdc0ac62f937987b254398495389a1622d53fc7798a099a6027e49f9dd51a332fc449fb25c0a76e53fad68e6829f2acfdc167860047160ded648a120048389c2c793cbb1abb6eb899cbb971ecca28106835f3fe5f58da38320f0232ecf6ee843b16b51fc85f48e81328d67fada76cabad10fda0a8912659d2b29c014fd9fa8faaf783e905faee15da27a803f669b3b045f77db24be2405ec2a1398b36f9486376cf6cdbef27bbab1f3c13d82a9cdd5d5d4bde35513ef897191a24ad1d8dfbd52227eeef2cbd2d4594a5251fcd777bb73724d8af10ccda982d8dfcfdf9ad6cd7fd86c

### CODE REVIEW

**Comment by ghost** [comment]
#approve 1d07c3ab91a3e4b3ddaa88bc01219c6420f469f959360074ba0ee46ac290fdc0ac62f937987b254398495389a1622d53fc7798a099a6027e49f9dd51a332fc449fb25c0a76e53fad68e6829f2acfdc167860047160ded648a120048389c2c793cbb1abb6eb899cbb971ecca28106835f3fe5f58da38320f0232ecf6ee843b16b51fc85f48e81328d67fada76cabad10fda0a8912659d2b29c014fd9fa8faaf783e905faee15da27a803f669b3b045f77db24be2405ec2a1398b36f9486376cf6cdbef27bbab1f3c13d82a9cdd5d5d4bde35513ef897191a24ad1d8dfbd52227eeef2cbd2d4594a5251fcd777bb73724d8af10ccda982d8dfcfdf9ad6cd7fd86c

**Comment by enomic** [comment]
use #approve instead of #authorize

**Comment by ghost** [comment]
#approve 1d07c3ab91a3e4b3ddaa88bc01219c6420f469f959360074ba0ee46ac290fdc0ac62f937987b254398495389a1622d53fc7798a099a6027e49f9dd51a332fc449fb25c0a76e53fad68e6829f2acfdc167860047160ded648a120048389c2c793cbb1abb6eb899cbb971ecca28106835f3fe5f58da38320f0232ecf6ee843b16b51fc85f48e81328d67fada76cabad10fda0a8912659d2b29c014fd9fa8faaf783e905faee15da27a803f669b3b045f77db24be2405ec2a1398b36f9486376cf6cdbef27bbab1f3c13d82a9cdd5d5d4bde35513ef897191a24ad1d8dfbd52227eeef2cbd2d4594a5251fcd777bb73724d8af10ccda982d8dfcfdf9ad6cd7fd86cv

**Comment by enomic** [comment]
Output is here: https://gist.github.com/8058b9792c056f9c54c5

**Comment by ghost** [comment]
:-( I suck

**Comment by cinderblock** [comment]
@w3dman What's wrong with this?

**Comment by ghost** [comment]
I'm not sure.  The log suggested the signature check failed: https://gist.github.com/8058b9792c056f9c54c5, perhaps due to a bug (seems fixed now?).  Anyway, the change was picked up in another pull request.

**Pull request closed without merging**
