### PR TITLE
Log more things

### PR DESCRIPTION
**Pull request by cinderblock**

### CODE REVIEW

**Comment by cinderblock** [comment]
I'm going to approve this PR in ~1 hour unless someone else does it for me or has any objections

**Comment by enomic** [comment]
#approve 2fd16aa3c44b34dd245e01d03a45ea0a378d9e196d3464ef06e4f524db3e330dde624f8499569ecbbd6b018d7aaefa20df1d5a43dc7beabfa52559d988442bebae322a236a098d6af83bce601a056df799ad74d800b00ffbc59bf97725a110c4a76ab82ac9b2da823827d4c2facc88403500fb9ad4248145a6eee1cdfcd62833b588a2a1f95ec40708c85100bcd64a72b8c0b20a97173b8fa4e80be0aba098c5412b513e189ef3edf228c134678adabef7617983fa39b03009de90b3080dbb9c21618f8ce863c642c398c1450e90206b0442b2c1322701f607c7e065c08f1fda5e33da5a0a4fb3b011e06bdd7ab81cbb49af353158a5452275c28e3dee33c76a

**Comment by enomic** [comment]
Output is here: https://gist.github.com/114d01233c52c1a9a7a1

**Comment by cinderblock** [comment]
Thanks @enomic! I guess someone liked the change :smile:

**Pull request merged**
