### PR TITLE
Cleaning up the homepage

### PR DESCRIPTION
**Pull request by drewry**

### CODE REVIEW

**Comment by drewry** [comment]
#approve 286f93714cda1688faf8dc2a59ecf70b49bcefd75a276da2b961efa2ffd0b231147237b2bfd3b77127d1c76f8782f6706f1ddb4165a822f0222bda2f3a6b77b597dd1cd2a4bea06cc2e223470a889921e25a5dce851dade1e9edeab30a16ab26e004964fb465663ecd557563995a9f0499ee8e460372c6b4aa76020f309a4656f453d779908cc62787a2b0ecc62c28835315369420c82a7f15d6a4f56d387528c56ee7a96828d5a87afeb3e532149732f007f430ce944836afdbfda581355fa224249b1a345c0369a7ae2defe93ecab38693dd4d6857f6a113882538b40f80305cd072b7ac7f3848585c1a443c4422f1ce8277b9d22b0ae1a9c3b275c7177365

**Comment by drewry** [comment]
I take it verify is broken again? @ZainRizvi

**Comment by ZainRizvi** [comment]
Yes it is, sorry about that. I've submitted the pull request but it needs keyholder access since the server is down and it can't accept #accept requests anymore

**Comment by drewry** [comment]
okie, can we ping the keyholder to do that?

**Comment by ZainRizvi** [comment]
I did
https://github.com/enomic/enomic/issues/29

**Comment by drewry** [comment]
#approve 286f93714cda1688faf8dc2a59ecf70b49bcefd75a276da2b961efa2ffd0b231147237b2bfd3b77127d1c76f8782f6706f1ddb4165a822f0222bda2f3a6b77b597dd1cd2a4bea06cc2e223470a889921e25a5dce851dade1e9edeab30a16ab26e004964fb465663ecd557563995a9f0499ee8e460372c6b4aa76020f309a4656f453d779908cc62787a2b0ecc62c28835315369420c82a7f15d6a4f56d387528c56ee7a96828d5a87afeb3e532149732f007f430ce944836afdbfda581355fa224249b1a345c0369a7ae2defe93ecab38693dd4d6857f6a113882538b40f80305cd072b7ac7f3848585c1a443c4422f1ce8277b9d22b0ae1a9c3b275c7177365

**Comment by enomic** [comment]
Ok, merging should work again now. Thanks for your patience, everyone!

**Comment by ZainRizvi** [comment]
#approve 286f93714cda1688faf8dc2a59ecf70b49bcefd75a276da2b961efa2ffd0b231147237b2bfd3b77127d1c76f8782f6706f1ddb4165a822f0222bda2f3a6b77b597dd1cd2a4bea06cc2e223470a889921e25a5dce851dade1e9edeab30a16ab26e004964fb465663ecd557563995a9f0499ee8e460372c6b4aa76020f309a4656f453d779908cc62787a2b0ecc62c28835315369420c82a7f15d6a4f56d387528c56ee7a96828d5a87afeb3e532149732f007f430ce944836afdbfda581355fa224249b1a345c0369a7ae2defe93ecab38693dd4d6857f6a113882538b40f80305cd072b7ac7f3848585c1a443c4422f1ce8277b9d22b0ae1a9c3b275c7177365

**Comment by enomic** [comment]
Output is here: https://gist.github.com/42c971d97f3767bd6378

**Comment by ZainRizvi** [comment]
heh, I used drewry's approval signature to approve this

**Comment by drewry** [comment]
haha nice :D

**Comment by ZainRizvi** [comment]
And the change broke the site :P

It had a bad git merge in server.js (it still contains the <<<<head, etc tags)

**Comment by ZainRizvi** [comment]
A staging zone would be nice so we stop builds which break the entire site

**Comment by drewry** [comment]
yes, and a domain pointing to the heroku would be cool

**Comment by arnoldblake** [comment]
Simply running the app locally would have caught the two so far.

**Comment by drewry** [comment]
Yes this is true, also something like travis-ci to check before merging would be ideal too.

**Pull request merged**
