### PR TITLE
Clarification on becoming a Hero

### PR DESCRIPTION
**Pull request by cinderblock**
I and many others are trying to approve our own PRs. This language should be clarified.

### CODE REVIEW

**Comment by enomic** [comment]
#approve a645b65cbafc63b56be9fce08379db9598eb804e0313e020508186b815e345c8ab31bb0f1f719a0d882f810566939dbc5847af138b03950d9c1f325fa355adb464e9440344213396f1cf64cbed60e5c4a5cb976cf17aedb3982e0e1b55936460878c02f96f17835330906795acc434cb6aa5cc4de7968871f891c5cd6c1b2a96ae0fde076f3ad0cca8080a9ab3fcfe77f9f9d1eaf4a392ed99696548b799725be2862af34786c23a42caae3215db3f551184015476b4d1c7feb8bd745ef97aef48375dd0341dbb905d45b7245618ccc6e8f1189be9d99f33ddd8fcea5c6798c79745a0d41ed69e6e804cd6aceab1207205d66273a6df78b32d88300af7c76802

**Comment by enomic** [comment]
#approve a645b65cbafc63b56be9fce08379db9598eb804e0313e020508186b815e345c8ab31bb0f1f719a0d882f810566939dbc5847af138b03950d9c1f325fa355adb464e9440344213396f1cf64cbed60e5c4a5cb976cf17aedb3982e0e1b55936460878c02f96f17835330906795acc434cb6aa5cc4de7968871f891c5cd6c1b2a96ae0fde076f3ad0cca8080a9ab3fcfe77f9f9d1eaf4a392ed99696548b799725be2862af34786c23a42caae3215db3f551184015476b4d1c7feb8bd745ef97aef48375dd0341dbb905d45b7245618ccc6e8f1189be9d99f33ddd8fcea5c6798c79745a0d41ed69e6e804cd6aceab1207205d66273a6df78b32d88300af7c76802

**Comment by cinderblock** [comment]
#approve 1bf0ea688c8551f0aed1a162a29a01d1d57de31e39f29cace843f990a7893eb4576486418c1a30c842945299f47436819463ab052b2f1a0e4d3272cb7e8daf0e5e6b39c7601e10372ec0a0198cbc26dd2ed7541e552c3743333e4507f632a5dc5505983075090af5f21a8ad63cff8c78312702338910a2d5343fbc0d090982ab9646a38e3d6d9ebd3fc12fd7f557ad204150d93776721779692795ba169ebaef5f3dd9ac699d4fcbdabb7f522eb9bd46a23576c03a8e6d8ee2e50be8720706ec48ed266c813cee83c6dfd10cd311cda68680d0e398c34b29615987c3af8a0a4f8a577010dc0efe6fec6be7f8ed54d036c5a23ba11b77b15dfdc56199f873faca

**Comment by cinderblock** [comment]
Interesting. I can approve but enomic cannot. A bug that only lets the first key work per chance?

**Comment by enomic** [comment]
Looks like you're the only real hero right now cinderblock. I can't sign anything, and the server logs are spitting out "Signature verification failed". I only ever tested it with one key in the hero list.

Can you fix it? Maybe you can log to a gist file and debug the problem? The bug is probably in the second half of verify.js, where we parse the keys

Please be careful not to break the app!

**Pull request merged**
