### PR TITLE
Include the #approve prefix when printing signatures

### PR DESCRIPTION
**Pull request by cinderblock**
I use this just to save me a tad of trouble. Anyone else care to approve this?

### CODE REVIEW

**Comment by cinderblock** [comment]
Uh, did I just accidentally edit my own pull request and add 2 more newer unrelated commits? I didn't mean to.

**Comment by ericvicenti** [comment]
#approve 8f400c4df3022124aedf959586b7436918949d9012d1d88714b582723f81e322438c218bdd9ef99ff716954bd1e851bc46c81032b990dde65bffe20bc93bf0163223b4ff0c291e0267224fe4640c02223846a595a83986094623a06848b0d9c4df413e4de233576029347af53859e8e911be156d38b81d125d57d380f909d50fa1b465a89a8324de48830d0e58aa9d63c99e98167e309286a354b075d8ac45471955828f332f1081d87897cf6f38a3e321c7e76c80f9b5996bb61faab8a2fa85384e0355475877cbc27cd3f657dce36a5500d128bfb033594a6fe08d2cef6d8604491495a1a0f5800d216ab908e17a9bacd6c81ff5c928c518846b9eed930d73

**Comment by enomic** [comment]
Output is here: https://gist.github.com/703f3c7cfe9909db81bf

**Comment by ericvicenti** [comment]
I can't sign commits for some reason.. @enomic, is something broken?

**Comment by cinderblock** [comment]
@ericvicenti, you were added in #8 it seem. Wrong key?

**Pull request merged**
