### PR TITLE
Switch to markdown

### PR DESCRIPTION
**Pull request by ericvicenti**
This is an obvious change- writing html like that is pretty barbaric

I moved the rules out of the main page to reduce clutter, and clarified the notion that the rules are really just guidelines. According to the OG doc:

> Anything that is technically possible is a legal move. These rules are only guidelines and documentation

### CODE REVIEW

**Comment by ericvicenti** [comment]
Usually I would wait for others to review and agree upon this, but just for fun I'm gonna try to sign it myself

**Comment by ericvicenti** [comment]
#approve 985e1b08ac6f13018dd93dd856f31819200caedb53548806d7d3f06c62117c298fd8c40064d41d1239aeb908726a9f2400cff4f01a942321ea122841ecfae3702ce2876018d3bae9ff379f051ed2f36813f309131db3c17a04b96e59f7ff7264a3e54830ee36669c44a1a202f2d449fce32477fdce229a869b3f1ae0ddcba15aa82d7cc8af30009cec42a176791a18bdc8833f03f841f9d3961dba47c3bea85dba89f0b0afd56d4ed9f56bf9bbd599b12e66233a50f202736efb138c3a66bce8d09ddc326626abdbe45995c622bdd5b2d5ad2bfacd8caf39f5404525e9425165a0710979dac10448e78186486ea63dd38003063a8f35faf4c1f5f6b9b3a3c9b4

**Comment by enomic** [comment]
Did your approval not work?

**Comment by enomic** [comment]
#approve 0365ff5c8cc0c3c8ac4b505a2b66011e6f4035c26bfb5ceb61c996c5908cf1dd131cc499d493f712a913d6ff94e3fe194b40f3f4de076bdbca5e2eff28616439dcb95247e1bc90fb122745b4a381687edc82c5017c73b55be8207afe48628e1dc3e24471f1af1fce6d3d3f304bc0e4b87e9879011fc9b48fd74b7d6fa59c6c40ef1ca9828b987590acbfb2c88f7e18763d30daccde6d83fa60f6e30de874b6159793ac9c1ae3144ab8a0ec1bf38da6c8467b320418d4a678275e1efc7bc5f5ab1b7a6d2bbefa8a7d9074adad799287415dab97626c0216a59c3bcb78149d46e7c2dd8b4fcf7648558419c02c74ecf283f1b50297d185ffa42e26fe2ab327292f

**Comment by ericvicenti** [comment]
No.. but it looks like yours did!

**Comment by enomic** [comment]
Ugh, something seems broken.. can you try another PR?

**Comment by enomic** [comment]
Sure

**Pull request merged**
